-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	bold = "rbxassetid://5402145483",
	italic = "rbxassetid://5402145537",
	strikethrough = "rbxassetid://5402145582",
	underline = "rbxassetid://5402145628",
}