-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	logo = "rbxassetid://5408247454",
	["logo-studio"] = "rbxassetid://5408279289",
	["paragraph-center"] = "rbxassetid://5408247536",
	["paragraph-left"] = "rbxassetid://5408187773",
	["paragraph-right"] = "rbxassetid://5408247637",
}